### ISSUE TITLE
Does not compile on Windows with Zig 0.13.0

### ISSUE THREAD

**Issue by hyt589** [nolanderc/glsl_analyzer#64]
# Problem

Running `zig build` with version 0.13.0 resulted in the following error:
```
C:\Users\hyt\workspace\projects\glsl_analyzer\build.zig:78:33: error: no field named 'path' in union 'Build.LazyPath'
        .root_source_file = .{ .path = "src/main.zig" },
                                ^~~~
C:\Users\hyt\scoop\apps\zig\0.13.0\lib\std\Build.zig:2171:22: note: union declared here
pub const LazyPath = union(enum) {
                     ^~~~~
referenced by:
    build: C:\Users\hyt\workspace\projects\glsl_analyzer\build.zig:9:25
    runBuild__anon_8955: C:\Users\hyt\scoop\apps\zig\0.13.0\lib\std\Build.zig:2117:37
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

Commit hash: 3514b232795858c6a1870832d2ff033eb54103ab

**Comment by nolanderc** [comment]
Fixed in 370520949f834ca1ed7d2913c5ed13092947f437. Available as v1.5.0.
